-- pvuv
CREATE TABLE IF NOT EXISTS pvuv
(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
	TIME_RANGE VARCHAR(128) NOT NULL COMMENT '时间区间',
	URL VARCHAR(128) NOT NULL COMMENT '当前url',
	UUID VARCHAR(128) COMMENT 'uuid',
	CHANNEL VARCHAR(128) COMMENT '渠道',
	CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	CREATED_BY  VARCHAR(128) NOT NULL DEFAULT 'sys' NOT NULL COMMENT '创建人',
	PRIMARY KEY(ID),
	KEY `INX_TIME_RANGE` (`TIME_RANGE`),
	KEY `INX_URL` (`URL`),
	KEY `INX_UUID` (`UUID`),
	KEY `INX_CHANNEL` (`CHANNEL`)
)ENGINE=MYISAM DEFAULT CHARSET=gbk AUTO_INCREMENT=1 COMMENT='pvuv';


alter table pclick add CHANNEL VARCHAR(128) COMMENT '渠道';
ALTER TABLE pclick ADD INDEX INX_CHANNEL ( `CHANNEL` ) ;



-- pclick
drop table pclick;
CREATE TABLE IF NOT EXISTS pclick
(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
	TIME_RANGE VARCHAR(128) NOT NULL COMMENT '时间区间',
	URL VARCHAR(128) NOT NULL COMMENT '当前url',
	AREA VARCHAR(128) NOT NULL COMMENT '主区域',
	POSITION VARCHAR(128) NOT NULL COMMENT '位置',
	PID VARCHAR(128) NOT NULL COMMENT '产品id',
	CHANNEL VARCHAR(128) COMMENT '渠道',
	COUNT int(11) DEFAULT NULL COMMENT '点击数',
	CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	CREATED_BY  VARCHAR(128) NOT NULL DEFAULT 'sys' NOT NULL COMMENT '创建人',
	PRIMARY KEY(ID),
	KEY `INX_TIME_RANGE` (`TIME_RANGE`),
	KEY `INX_URL` (`URL`),
	KEY `INX_AREA` (`AREA`),
	KEY `INX_POSITION` (`POSITION`),
	KEY `INX_PID` (`PID`),
	KEY `INX_CHANNEL` (`CHANNEL`)
)ENGINE=MYISAM DEFAULT CHARSET=gbk AUTO_INCREMENT=1 COMMENT='pclick';


